apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mazarbul
  title: Mazarbul
  description: Procurement + budget tracking (FastAPI + Nuxt) with audit logging and access control.
  tags:
    - fastapi
    - nuxt
    - sqlite
    - procurement
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:digital-apps
  providesApis: []
