apiVersion: v2
name: ebrose
description: Ebrose Procurement Tracking System
version: 0.7.1
appVersion: "0.7.1"
keywords:
  - procurement
  - tracking
  - fastapi
  - nuxt
home: https://github.com/kwatog/ebrose
sources:
  - https://github.com/kwatog/ebrose
maintainers:
  - name: Ebrose Team
    email: admin@ebrose.local
